name: 'Saplings - AI CKEditor Experience'
description: 'Configures CKEditor for AI translation and content generation.'
type: Editor
recipes:
  - core/recipes/full_html_format_editor
install:
  # Core.
  - ckeditor5
  - editor
  - file
  - filter
  # Contrib.
  - ai
  - ai_ckeditor
  - key
  - provider_openai
